apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: singleIngress1
  namespace: default
  annotations:
  # See the k8s-bigip-ctlr documentation for information about
  # all Ingress Annotations
  # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest/#supported-ingress-annotations
    virtual-server.f5.com/ip: "1.2.3.4"
    virtual-server.f5.com/partition: "k8s"
spec:
  backend:
    # The name of the Service you want to expose to external traffic
    serviceName: myService
    servicePort: 80
