# Deploy a BIG-IP Controller instance in the custA-test and custA-prod namespaces
# Manages the customerA partition on the BIG-IP system
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: custA_k8s-bigip-ctlr
  namespace: bigip-controllers
spec:
  replicas: 1
  template:
    metadata:
      name: custA_k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: bigip-ctlr-serviceaccountA
      containers:
        - name: custA_k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:1.3.0"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: custA_bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: custA_bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-partition=customerA",
            "--bigip-url=10.190.24.171",
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--use-secrets=true",
            "--namespace=custA_test",
            "--namespace=custA_prod",
            "--pool-member-type=cluster",
            ...
            ]
---
# Ingress for all hosts in custA_test
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test.vs
  namespace: custA_test
  annotations:
    # IP address of a BIG-IP pool member
    virtual-server.f5.com/ip: "1.2.3.4"
    # BIG-IP partition
    virtual-server.f5.com/partition: "customerA"
    # Load balancing algorithm
    virtual-server.f5.com/balance: "least-connections-node"
spec:
  rules:
  - http:
      paths:
      - path: /myApp1
        backend:
          serviceName: myService1
          servicePort: 80
      - path: /myApp2
        backend:
          serviceName: myService2
          servicePort: 80
---
# Ingress for all hosts in custA_prod
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prod.vs
  namespace: custA_prod
  annotations:
    # IP address of a BIG-IP pool member
    virtual-server.f5.com/ip: "10.12.13.14"
    # BIG-IP partition
    virtual-server.f5.com/partition: "customerA"
    # Load balancing algorithm
    virtual-server.f5.com/balance: "least-connections-node"
spec:
  rules:
  - http:
      paths:
      - path: /myApp1
        backend:
          serviceName: myService1
          servicePort: 80
      - path: /myApp2
        backend:
          serviceName: myService2
          servicePort: 80
