# Deploy a BIG-IP Controller instance in the k8s_test namespace
# Manages the test partition on the BIG-IP system
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test_k8s-bigip-ctlr
  namespace: k8s_test
spec:
  replicas: 1
  template:
    metadata:
      name: test_k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: bigip-ctlr-serviceaccount
      containers:
        - name: test_k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:1.3.0"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-partition=test",
            "--bigip-url=10.190.24.171",
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--use-secrets=true",
            "--pool-member-type=cluster",
            ...
            ]

---
# Deploy a BIG-IP Controller instance in the k8s_prod namespace
# Manages the prod partition on the BIG-IP system
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prod_k8s-bigip-ctlr
  namespace: k8s_prod
spec:
  replicas: 1
  template:
    metadata:
      name: prod_k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: bigip-ctlr-serviceaccount
      containers:
        - name: prod_k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:1.2.0"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-partition=prod",
            "--bigip-url=10.190.24.171",
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "use-secrets=true",
            ...
            ]

---
# Deploy the f5.http iApp in the test partition
kind: ConfigMap
apiVersion: v1
metadata:
  name: test.http
  namespace: k8s_test
  labels:
    f5type: virtual-server
data:
  # schema v.0.1.4 is required as of k8s-bigip-ctlr v1.3.0
  schema: "f5schemadb://bigip-virtual-server_v0.1.4.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "myService",
          "servicePort": 3000
        },
        "frontend": {
          "partition": "test",
          "iapp": "/Common/f5.http",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "myService_f5.http iApp"
          },
          "iappVariables": {
            "monitor__monitor": "/#create_new#",
            "monitor__response": "none",
            "monitor__uri": "/",
            "net__client_mode": "wan",
            "net__server_mode": "lan",
            "pool__addr": "127.0.0.2",
            "pool__pool_to_use": "/#create_new#",
            "pool__port": "4430"
          }
        }
      }
    }

