apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          # replace the version as needed
          image: "f5networks/k8s-bigip-ctlr:1.4.2"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.11.12.13",
            "--bigip-partition=k8s",
            # The Controller watches all namespaces by default.
            # To manage a single namespace, or multiple namespaces, provide a
            # single entry for each. For example:
            # "--namespace=test",
            # "--namespace=prod"
            # The Controller can access Secrets by default;
            # set to "false" if you only want to use SSL profiles that are
            # already set up on your BIG-IP device, e.g.
            # "--use-secrets=false",
            # The Controller can use local DNS to resolve hostnames;
            # defaults to LOOKUP; can be replaced with custom DNS server IP
            # or left blank (introduced in v1.3.0)
            "--resolve-ingress-names=<DNS_SERVER_IP_ADDRESS>",
            # The Controller can assign an IP address to Ingress resources
            # using the "controller-default" annotation;
            # provide the IP address to use as the default below
            # (introduced in v1.4.0)
            "--default-ingress-ip=1.2.3.4",
            # Runs the BIG-IP Controller in cluster mode (see docs for info:
            # http://clouddocs.f5.com/containers/latest/kubernetes/kctlr-modes.html)
            "--pool-member-type=cluster",
            # If the BIG-IP is connected to a flannel network, provide the
            # BIG-IP tunnel name (introduced in v1.4.0):
            "--flannel-name=<bigip_tunnel_name>"
            ]
      imagePullSecrets:
        - name: f5-docker-images
        - name: bigip-login
