apiVersion: v1
kind: Node
metadata:
  name: bigip
  annotations:
    # This is the MAC address of the VXLAN tunnel you have created on the
    # BIG-IP device
    flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"ab:12:cd:34:ef:56"}'
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    # This address is the BIG-IP VTEP (internal address) in the Flannel VXLAN
    flannel.alpha.coreos.com/public-ip: 172.16.1.3
spec:
  # This defines the Flannel subnet for the BIG-IP device. Be sure this subnet
  # does not collide with the subnets of the other Nodes. The BIG-IP device's
  # self-ip address will be defined in this subnet.
  podCIDR: 10.244.30.0/24
