kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s.http
  namespace: default
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "myService",
          "servicePort": 80
        },
        "frontend": {
          "partition": "k8s",
          "iapp": "/Common/f5.http",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "myService_f5.http iApp"
          },
          "iappVariables": {
            "monitor__monitor": "/#create_new#",
            "monitor__response": "none",
            "monitor__uri": "/",
            "net__client_mode": "wan",
            "net__server_mode": "lan",
            "pool__addr": "127.0.0.2",
            "pool__pool_to_use": "/#create_new#",
            "pool__port": "4430"
          }
        }
      }
    }
